### ISSUE TITLE
Feature: User can search for a movie to review

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/movii#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for the movie they would like to review

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be presented with an empty search bar with a search button. The user can type in keywords to search for and click the search button to generate a results page. On the results page, there will be cards for each movie result that matches the keywords. Each movie result has an image of a movie and its title. When the user clicks the info icon, a modal will appear with a dialogue box with more details on the movie. The dialogue box can be closed by clicking the x icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![search mobile 1](https://user-images.githubusercontent.com/96809909/156465951-bea754d6-888d-4f0f-aa4f-9abadb96aedf.png)
![search mobile 2](https://user-images.githubusercontent.com/96809909/156466063-e731c2f4-1570-4c24-8329-59f0a6112226.png)
![search desktop 1](https://user-images.githubusercontent.com/96809909/156465813-1e39ef8e-365c-4448-9b72-4c6e42a3f23f.png)
![search desktop 2](https://user-images.githubusercontent.com/96809909/156465816-1eccd7e4-4f0e-46ea-84c1-c80e76b72be6.png)
![search desktop 3](https://user-images.githubusercontent.com/96809909/156465818-d26a430c-ea27-428e-bf5a-a96041e0ee19.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="search-view"] to the HTML.
- [x] Add a form element to your HTML document
- [x] Within the form element, add an input element with a movie title label
- [x] Add a button element labeled SEARCH under the input element
- [x] Create a nav bar with the logo inside it
- [x] Create an anchor for the SEARCH view
- [x] Add an empty unordered list to the `div[data-view="results-view"]` element in the HTML.
- [x] Add some dummy search results to the unordered list in the HTML and style them to match the wireframe
- [x] Check that the search results list looks good on both mobile and desktop screens.
- [x] In your main.js file, query for the search input element
- [x] Concatenate the search input value with the https url and apikey
- [x] Store the url in a variable
- [x] Create a new XMLHttpRequest object
- [x] Open a http request for the keyword
- [x] Send the http request
- [x] Define a function that takes a single search result object and returns a DOM tree that matches one of the example search result
- [x] Use a loop to create a DOM tree for each search result in the HTTP response and append it to the page when the submit button is clicked
- [x] Define a function to swap from the search view to the results view when the SEARCH button is clicked
- [x] Define a function to swap from the results view to the search view when the SEARCH anchor is clicked
- [x] Remove the example HTML search result once the user's search results are successfully being appended to the DOM on page load.
- [x] Create modal for movie details. Add dummy data
- [x] Add event listener for info icon. When the icon is clicked, the movie details modal appears
- [x] Define a function to create a DOM tree for the movie details dialogue box
- [x] Add event listener for the close icon. When the icon is clicked, the modal will not be visible
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
