### ISSUE TITLE
Feature: User can post a review

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/movii#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can post a review for a movie
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can create a movie review by filling out the review form. The user can set a star rating by clicking on the star that corresponds with their rating. The user can fill out the movie title, poster url, and review. All the inputs are required. When the user submits the form, the form is reset and the user's review is stored in the data model.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![create mobile](https://user-images.githubusercontent.com/96809909/156510609-dc8b4216-2d0f-4ace-9764-9c10ce0d0702.png)
![create desktop 01](https://user-images.githubusercontent.com/96809909/156510610-405e0878-01a5-4f59-a3d9-8afc8e0fa242.png)
![create desktop 02](https://user-images.githubusercontent.com/96809909/156510613-8fb7d4b7-9260-471a-b6a0-465188933006.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="review-form"]` to the HTML.
- [x] Add a form for creating a review to the `div[data-view="review-form"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the review form `required`.
- [x] Listen for `'click'` events on the `results-list`. If the event.target matches a review-button, populate the movie title form input and poster url form input with the search result's movie title and poster url.
- [x] Update the `src` attribute of the poster preview with the poster url input's value
- [x] Define a function to set the star rating for the movie. 
- [x] Listen for `'submit'` events on the poster review form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextReviewId` to the object. The property name should be reviewId.
  - [x] Increment the `nextReviewId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
- [x] Verify that new reviews are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new review receives an incrementing `reviewId`.
- [x] Add an anchor in the nav bar for posting a review
- [x] Update the view swapping function. Clicking on the Post anchor should make the review-form view appear.
- [x] Ensure that refreshing the web app on a certain view lets the user stay on the same view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
