### ISSUE TITLE
Feature: User can view the review

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/movii#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the review they have written in the reviews list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the review form has been submitted, the user can view their reviews in the reviews list. The reviews are displayed in reverse chronological order (newest at the very top).  Submitting a review automatically takes the user to the reviews list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view mobile](https://user-images.githubusercontent.com/96809909/156824699-510a5c90-4d5e-4068-95b0-de79a4c2658c.png)
![view desktop](https://user-images.githubusercontent.com/96809909/156824704-774dacbe-995c-416d-9751-b23063d627ff.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="reviews"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="reviews"]` element in the HTML.
- [x] Add some dummy movie reviews to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the reviews list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single movie `review` object and returns a DOM tree that matches one of the example reviews in the HTML.
- [x] Use a loop to create a DOM tree for each review in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML review once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Reviews.
- [x] Add a NEW button to create a new review
- [x] Ensure that submitting a new review also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new review automatically shows the `'reviews'` view without reloading the page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
