### ISSUE TITLE
Feature: User can edit a review

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/movii#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a review they have submitted.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Each review has a pen icon for the user to click. Clicking on a pen icon shows the review form again. The page heading is updated to say “Edit Review”. The image preview shows the original poster URL. Changing the poster URL updates the image preview. Saving the changes automatically shows the review list again. The updated review is still in the same ordering as it was before.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![edit mobile](https://user-images.githubusercontent.com/96809909/156907646-cb8978ff-8d76-46ef-b728-402853ec82c5.png)
![edit desktop 01](https://user-images.githubusercontent.com/96809909/156907649-39c16e35-3d3f-4843-82bb-3fc9accfe6a0.png)
![edit desktop 02](https://user-images.githubusercontent.com/96809909/156907650-b92632f7-7a7f-4c0d-9087-8156dcf57749.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the review rendering function to include a dom element for the edit icon for each rendered review.
- [x] Ensure that each rendered review is given a `data-review-id` attribute indicating which review it is.
- [x] Listen for clicks on the parent element of all rendered reviews.
- [x] Show the review form if an edit icon was clicked.
- [x] Find the matching review object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the review form with the clicked review's values from the object found in the data model.
- [x] Update the review form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Update the review form's submit handler function to conditionally add a new review DOM tree or replace the existing one.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
