### ISSUE TITLE
Feature: User can delete a review

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/movii#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a review they have submitted.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a review is being edited, there is an option to delete it. Clicking on “Delete Review” displays a modal. The modal has a “Cancel” button that closes the modal. The modal has a “Delete” button that: closes the modal, removes the entry, and shows the reviews list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![delete mobile](https://user-images.githubusercontent.com/96809909/157152784-a69acc97-5209-4bc2-ba3c-d1e51830cc6f.png)
![delete desktop 01](https://user-images.githubusercontent.com/96809909/157152788-5729e920-2af5-49e7-a3ee-b87f062579ec.png)
![delete desktop 02](https://user-images.githubusercontent.com/96809909/157152791-eda38106-8bc5-403d-abe0-f8f5d621580e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for deleting a review to the review form that only appears if the user is editing an review.
- [x] Show a confirmation modal when the user clicks the Delete click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the review from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the Reviews list if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
